"""Auto-generated registry of every Virtuous CRM+ API endpoint.

Generated from the official Virtuous API reference (docs.virtuoussoftware.com).
Each entry describes one endpoint: HTTP method, path (with :placeholders for
path parameters), a human title, the resource group it belongs to, whether it is
read-only, and its path/query parameter names.

This registry powers the generic discovery + call tools in server.py, giving the
MCP full coverage of the API without one Python function per endpoint.

DO NOT hand-edit; regenerate from the source collection instead.
"""

from __future__ import annotations

from typing import TypedDict


class Endpoint(TypedDict):
    method: str
    path: str
    title: str
    resource: str
    read: bool
    path_params: list[str]
    query_params: list[str]


ENDPOINTS: list[Endpoint] = [
    {"method": 'GET', "path": '/api/Campaign/:campaignId', "title": 'Get Campaign', "resource": 'Campaign', "read": True, "path_params": ['campaignId'], "query_params": []},
    {"method": 'GET', "path": '/api/Campaign/GetStepsByCampaignId/:campaignId', "title": 'Gets Campaign Steps', "resource": 'Campaign', "read": True, "path_params": ['campaignId'], "query_params": []},
    {"method": 'POST', "path": '/api/Campaign/Query', "title": 'Query Campaigns', "resource": 'Campaign', "read": True, "path_params": [], "query_params": ['skip', 'take']},
    {"method": 'GET', "path": '/api/Campaign/QueryOptions', "title": 'Get Campaign Query Options', "resource": 'Campaign', "read": True, "path_params": [], "query_params": []},
    {"method": 'POST', "path": '/api/Communication', "title": 'Create Communication', "resource": 'Communication', "read": False, "path_params": [], "query_params": []},
    {"method": 'GET', "path": '/api/Communication/:communicationId', "title": 'Get Communication', "resource": 'Communication', "read": True, "path_params": ['communicationId'], "query_params": []},
    {"method": 'GET', "path": '/api/Communication/ByCampaign/:campaignId', "title": 'Get Communications for a Campaign', "resource": 'Communication', "read": True, "path_params": ['campaignId'], "query_params": ['filter', 'sortBy', 'descending', 'skip', 'take']},
    {"method": 'GET', "path": '/api/Communication/ChannelTypes', "title": 'Get Channel Types', "resource": 'Communication', "read": True, "path_params": [], "query_params": []},
    {"method": 'GET', "path": '/api/Communication/CommunicationTypes', "title": 'Get Communication Types', "resource": 'Communication', "read": True, "path_params": [], "query_params": []},
    {"method": 'POST', "path": '/api/Communication/Query', "title": 'Query Communications', "resource": 'Communication', "read": True, "path_params": [], "query_params": ['skip', 'take']},
    {"method": 'GET', "path": '/api/Communication/QueryOptions', "title": 'Communication Query Options', "resource": 'Communication', "read": True, "path_params": [], "query_params": []},
    {"method": 'POST', "path": '/api/Contact', "title": 'Create a Contact', "resource": 'Contact', "read": False, "path_params": [], "query_params": []},
    {"method": 'GET', "path": '/api/Contact/:contactId', "title": 'Get a Contact', "resource": 'Contact', "read": True, "path_params": ['contactId'], "query_params": []},
    {"method": 'PUT', "path": '/api/Contact/:contactId', "title": 'Update a Contact', "resource": 'Contact', "read": False, "path_params": ['contactId'], "query_params": []},
    {"method": 'DELETE', "path": '/api/Contact/:contactId/Collection/:collectionInstanceId', "title": 'Delete Collection for a Contact', "resource": 'Contact', "read": False, "path_params": ['contactId', 'collectionInstanceId'], "query_params": []},
    {"method": 'PUT', "path": '/api/Contact/:contactId/Collection/:collectionInstanceId', "title": 'Update Collection for a Contact', "resource": 'Contact', "read": False, "path_params": ['contactId', 'collectionInstanceId'], "query_params": []},
    {"method": 'POST', "path": '/api/Contact/:contactId/Collection/:customCollectionId', "title": 'Create Collection for a Contact', "resource": 'Contact', "read": False, "path_params": ['contactId', 'customCollectionId'], "query_params": []},
    {"method": 'GET', "path": '/api/Contact/:referenceSource/:referenceId', "title": 'Get a Contact by Reference Source and ID', "resource": 'Contact', "read": True, "path_params": ['referenceSource', 'referenceId'], "query_params": []},
    {"method": 'GET', "path": '/api/Contact/Activity', "title": 'Get the Activity for the Contacts the current user is following', "resource": 'Contact', "read": True, "path_params": [], "query_params": ['skip', 'take']},
    {"method": 'PUT', "path": '/api/Contact/Archive/:contactId', "title": 'Archive a Contact', "resource": 'Contact', "read": False, "path_params": ['contactId'], "query_params": []},
    {"method": 'POST', "path": '/api/Contact/Batch', "title": 'Create a Contact Import that will be processed for changes and duplicates', "resource": 'Contact', "read": False, "path_params": [], "query_params": []},
    {"method": 'GET', "path": '/api/Contact/ByReference/:referenceId', "title": 'Get a Contact by Reference ID', "resource": 'Contact', "read": True, "path_params": ['referenceId'], "query_params": []},
    {"method": 'GET', "path": '/api/Contact/ByTag/:tagId', "title": 'Get Contacts by Tag ID', "resource": 'Contact', "read": True, "path_params": ['tagId'], "query_params": ['filter', 'sortBy', 'descending', 'skip', 'take']},
    {"method": 'GET', "path": '/api/Contact/CustomCollections', "title": 'Get Custom Collections for Contacts', "resource": 'Contact', "read": True, "path_params": [], "query_params": []},
    {"method": 'GET', "path": '/api/Contact/CustomFields', "title": 'Get Contact Custom Fields Available', "resource": 'Contact', "read": True, "path_params": [], "query_params": []},
    {"method": 'GET', "path": '/api/Contact/Find', "title": 'Find a Contact by Email Address or Reference Source and ID', "resource": 'Contact', "read": True, "path_params": [], "query_params": ['email', 'referenceSource', 'referenceId']},
    {"method": 'GET', "path": '/api/Contact/Following', "title": 'Get the Contacts the current user is following', "resource": 'Contact', "read": True, "path_params": [], "query_params": ['skip', 'take']},
    {"method": 'GET', "path": '/api/Contact/Prefixes', "title": 'Get Contact Name Prefixes and Titles', "resource": 'Contact', "read": True, "path_params": [], "query_params": []},
    {"method": 'POST', "path": '/api/Contact/Proximity', "title": 'Find all Contacts within a given proximity of a geocoordinate', "resource": 'Contact', "read": True, "path_params": [], "query_params": ['skip', 'take']},
    {"method": 'POST', "path": '/api/Contact/Query', "title": 'Query Contacts with Abbreviated Details', "resource": 'Contact', "read": True, "path_params": [], "query_params": ['skip', 'take']},
    {"method": 'POST', "path": '/api/Contact/Query/FullContact', "title": 'Query Contacts with Full Details', "resource": 'Contact', "read": True, "path_params": [], "query_params": ['skip', 'take']},
    {"method": 'GET', "path": '/api/Contact/QueryOptions', "title": 'Get Contact Query Options', "resource": 'Contact', "read": True, "path_params": [], "query_params": []},
    {"method": 'GET', "path": '/api/Contact/Receipts', "title": 'Receipts', "resource": 'Contact', "read": True, "path_params": [], "query_params": ['email', 'skip', 'take']},
    {"method": 'GET', "path": '/api/Contact/Receipts/:receiptId', "title": 'Get Receipt', "resource": 'Contact', "read": True, "path_params": ['receiptId'], "query_params": []},
    {"method": 'POST', "path": '/api/Contact/Search', "title": 'Find all Contacts that match, fully or partially, the given search parameters', "resource": 'Contact', "read": True, "path_params": [], "query_params": ['skip', 'take']},
    {"method": 'PUT', "path": '/api/Contact/ToggleFollow/:contactId', "title": 'Follow or Unfollow a Contact for the current user', "resource": 'Contact', "read": False, "path_params": ['contactId'], "query_params": []},
    {"method": 'POST', "path": '/api/Contact/Transaction', "title": 'Create a Contact that will go through the import process', "resource": 'Contact', "read": False, "path_params": [], "query_params": []},
    {"method": 'GET', "path": '/api/Contact/Types', "title": 'Get Contact Types', "resource": 'Contact', "read": True, "path_params": [], "query_params": []},
    {"method": 'PUT', "path": '/api/Contact/Unarchive/:contactId', "title": 'Unarchive a Contact', "resource": 'Contact', "read": False, "path_params": ['contactId'], "query_params": []},
    {"method": 'POST', "path": '/api/ContactAddress', "title": 'Create a Contact Address', "resource": 'ContactAddress', "read": False, "path_params": [], "query_params": []},
    {"method": 'DELETE', "path": '/api/ContactAddress/:contactAddressId', "title": 'Delete a Contact Address', "resource": 'ContactAddress', "read": False, "path_params": ['contactAddressId'], "query_params": []},
    {"method": 'GET', "path": '/api/ContactAddress/:contactAddressId', "title": 'Get a Contact Address', "resource": 'ContactAddress', "read": True, "path_params": ['contactAddressId'], "query_params": []},
    {"method": 'PUT', "path": '/api/ContactAddress/:contactAddressId', "title": 'Update a Contact Address', "resource": 'ContactAddress', "read": False, "path_params": ['contactAddressId'], "query_params": []},
    {"method": 'PUT', "path": '/api/ContactAddress/Archive/:contactAddressId', "title": 'Archive a Contact Address', "resource": 'ContactAddress', "read": False, "path_params": ['contactAddressId'], "query_params": []},
    {"method": 'GET', "path": '/api/ContactAddress/ByContact/:contactId', "title": 'Get the Contact Addresses for a Contact', "resource": 'ContactAddress', "read": True, "path_params": ['contactId'], "query_params": []},
    {"method": 'PUT', "path": '/api/ContactAddress/Unarchive/:contactAddressId', "title": 'Unarchive a Contact Address', "resource": 'ContactAddress', "read": False, "path_params": ['contactAddressId'], "query_params": []},
    {"method": 'POST', "path": '/api/ContactIndividual', "title": 'Create an Individual', "resource": 'ContactIndividual', "read": False, "path_params": [], "query_params": []},
    {"method": 'DELETE', "path": '/api/ContactIndividual/:contactIndividualId', "title": 'Delete an Individual', "resource": 'ContactIndividual', "read": False, "path_params": ['contactIndividualId'], "query_params": []},
    {"method": 'GET', "path": '/api/ContactIndividual/:contactIndividualId', "title": 'Get an Individual', "resource": 'ContactIndividual', "read": True, "path_params": ['contactIndividualId'], "query_params": []},
    {"method": 'PUT', "path": '/api/ContactIndividual/:contactIndividualId', "title": 'Update an Individual', "resource": 'ContactIndividual', "read": False, "path_params": ['contactIndividualId'], "query_params": []},
    {"method": 'GET', "path": '/api/ContactIndividual/:contactIndividualId/Avatar', "title": 'Gets the avatar for a specified contact individual', "resource": 'ContactIndividual', "read": True, "path_params": ['contactIndividualId'], "query_params": []},
    {"method": 'POST', "path": '/api/ContactIndividual/:contactIndividualId/Avatar', "title": 'Upload the avatar for an Individual', "resource": 'ContactIndividual', "read": False, "path_params": ['contactIndividualId'], "query_params": []},
    {"method": 'DELETE', "path": '/api/ContactIndividual/:contactIndividualId/Collection/:collectionId', "title": 'Delete Collection for an Individual', "resource": 'ContactIndividual', "read": False, "path_params": ['contactIndividualId', 'collectionId'], "query_params": ['collectionInstanceId']},
    {"method": 'PUT', "path": '/api/ContactIndividual/:contactIndividualId/Collection/:collectionInstanceId', "title": 'Update Collection for an Individual', "resource": 'ContactIndividual', "read": False, "path_params": ['contactIndividualId', 'collectionInstanceId'], "query_params": []},
    {"method": 'POST', "path": '/api/ContactIndividual/:contactIndividualId/Collection/:customCollectionId', "title": 'Create Collection for an Individual', "resource": 'ContactIndividual', "read": False, "path_params": ['contactIndividualId', 'customCollectionId'], "query_params": []},
    {"method": 'GET', "path": '/api/ContactIndividual/ByContact/:contactId', "title": 'Get Individuals for a Contact', "resource": 'ContactIndividual', "read": True, "path_params": ['contactId'], "query_params": []},
    {"method": 'GET', "path": '/api/ContactIndividual/CustomCollections', "title": 'Get Custom Collections for Individuals', "resource": 'ContactIndividual', "read": True, "path_params": [], "query_params": []},
    {"method": 'GET', "path": '/api/ContactIndividual/CustomFields', "title": 'Gets the custom fields for contact individuals', "resource": 'ContactIndividual', "read": True, "path_params": [], "query_params": []},
    {"method": 'GET', "path": '/api/ContactIndividual/Find', "title": 'Find an individual by email address', "resource": 'ContactIndividual', "read": True, "path_params": [], "query_params": ['email']},
    {"method": 'POST', "path": '/api/ContactIndividual/Query', "title": 'Query Individuals', "resource": 'ContactIndividual', "read": True, "path_params": [], "query_params": ['skip', 'take']},
    {"method": 'GET', "path": '/api/ContactIndividual/QueryOptions', "title": 'Get Individual Query Options', "resource": 'ContactIndividual', "read": True, "path_params": [], "query_params": []},
    {"method": 'GET', "path": '/api/ContactIndividual/{contactIndividualId}/EmailList', "title": 'Get Email Lists for an Individual', "resource": 'ContactIndividual', "read": True, "path_params": [], "query_params": ['skip', 'take']},
    {"method": 'POST', "path": '/api/ContactMethod', "title": 'Create a Contact Method for an Individual', "resource": 'ContactMethod', "read": False, "path_params": [], "query_params": []},
    {"method": 'DELETE', "path": '/api/ContactMethod/:contactMethodId', "title": 'Delete a Contact Method', "resource": 'ContactMethod', "read": False, "path_params": ['contactMethodId'], "query_params": []},
    {"method": 'GET', "path": '/api/ContactMethod/:contactMethodId', "title": 'Get a Contact Method', "resource": 'ContactMethod', "read": True, "path_params": ['contactMethodId'], "query_params": []},
    {"method": 'PUT', "path": '/api/ContactMethod/:contactMethodId', "title": 'Update a Contact Method', "resource": 'ContactMethod', "read": False, "path_params": ['contactMethodId'], "query_params": []},
    {"method": 'PUT', "path": '/api/ContactMethod/Archive/:contactMethodId', "title": 'Archive a Contact Method', "resource": 'ContactMethod', "read": False, "path_params": ['contactMethodId'], "query_params": []},
    {"method": 'GET', "path": '/api/ContactMethod/RelatedTypes', "title": 'Get Contact Methods Types related to the Base Type', "resource": 'ContactMethod', "read": True, "path_params": [], "query_params": ['name']},
    {"method": 'GET', "path": '/api/ContactMethod/Types', "title": 'Get Contact Method Types', "resource": 'ContactMethod', "read": True, "path_params": [], "query_params": []},
    {"method": 'PUT', "path": '/api/ContactMethod/Unarchive/:contactMethodId', "title": 'Unarchive a Contact Method', "resource": 'ContactMethod', "read": False, "path_params": ['contactMethodId'], "query_params": []},
    {"method": 'POST', "path": '/api/ContactNote', "title": 'Create a Note for a Contact', "resource": 'ContactNote', "read": False, "path_params": [], "query_params": []},
    {"method": 'DELETE', "path": '/api/ContactNote/:noteId', "title": 'Delete a Note', "resource": 'ContactNote', "read": False, "path_params": ['noteId'], "query_params": []},
    {"method": 'GET', "path": '/api/ContactNote/:noteId', "title": 'Get a Note', "resource": 'ContactNote', "read": True, "path_params": ['noteId'], "query_params": []},
    {"method": 'PUT', "path": '/api/ContactNote/:noteId', "title": 'Update a Note', "resource": 'ContactNote', "read": False, "path_params": ['noteId'], "query_params": []},
    {"method": 'GET', "path": '/api/ContactNote/ByContact/:contactId', "title": 'Get the Notes for a Contact', "resource": 'ContactNote', "read": True, "path_params": ['contactId'], "query_params": ['sortBy', 'descending', 'skip', 'take']},
    {"method": 'GET', "path": '/api/ContactNote/CustomFields', "title": 'Gets the custom fields for contact note', "resource": 'ContactNote', "read": True, "path_params": [], "query_params": []},
    {"method": 'POST', "path": '/api/ContactNote/Email', "title": 'Create a Note using an Email', "resource": 'ContactNote', "read": False, "path_params": [], "query_params": []},
    {"method": 'GET', "path": '/api/ContactNote/Important/ByContact/:contactId', "title": 'Get the Important Notes for a Contact', "resource": 'ContactNote', "read": True, "path_params": ['contactId'], "query_params": ['sortBy', 'descending', 'skip', 'take']},
    {"method": 'POST', "path": '/api/ContactNote/Query', "title": 'Query Contact Notes', "resource": 'ContactNote', "read": True, "path_params": [], "query_params": ['skip', 'take']},
    {"method": 'GET', "path": '/api/ContactNote/QueryOptions', "title": 'Get Contact Note Query Options', "resource": 'ContactNote', "read": True, "path_params": [], "query_params": []},
    {"method": 'GET', "path": '/api/ContactNote/Types', "title": 'Get Contact Note Types', "resource": 'ContactNote', "read": True, "path_params": [], "query_params": []},
    {"method": 'POST', "path": '/api/ContactReference', "title": 'Create a Contact Reference', "resource": 'ContactReference', "read": False, "path_params": [], "query_params": []},
    {"method": 'DELETE', "path": '/api/ContactReference/:referenceSource', "title": 'Delete a Contact Reference', "resource": 'ContactReference', "read": False, "path_params": ['referenceSource'], "query_params": ['referenceId']},
    {"method": 'POST', "path": '/api/ContactTag', "title": 'Create a Contact Tag', "resource": 'ContactTag', "read": False, "path_params": [], "query_params": []},
    {"method": 'DELETE', "path": '/api/ContactTag/:contactTagId', "title": 'Delete a Contact Tag', "resource": 'ContactTag', "read": False, "path_params": ['contactTagId'], "query_params": []},
    {"method": 'GET', "path": '/api/ContactTag/ByContact/:contactId', "title": 'Get Tags for a Contact', "resource": 'ContactTag', "read": True, "path_params": ['contactId'], "query_params": ['skip', 'take']},
    {"method": 'POST', "path": '/api/Email/Search', "title": 'Get Emails', "resource": 'Email', "read": True, "path_params": [], "query_params": ['skip', 'take']},
    {"method": 'POST', "path": '/api/Email/Send', "title": 'Send an Email to a list of Contacts', "resource": 'Email', "read": False, "path_params": [], "query_params": []},
    {"method": 'POST', "path": '/api/EmailList', "title": 'Add Individuals to an Email List', "resource": 'EmailList', "read": False, "path_params": [], "query_params": []},
    {"method": 'POST', "path": '/api/EmailList/Search', "title": 'Search for an Email List', "resource": 'EmailList', "read": True, "path_params": [], "query_params": ['skip', 'take']},
    {"method": 'GET', "path": '/api/Event', "title": 'Get Events', "resource": 'Event', "read": True, "path_params": [], "query_params": ['skip', 'take']},
    {"method": 'POST', "path": '/api/Event', "title": 'Create an Event', "resource": 'Event', "read": False, "path_params": [], "query_params": []},
    {"method": 'DELETE', "path": '/api/Event/:eventId', "title": 'Delete an Event', "resource": 'Event', "read": False, "path_params": ['eventId'], "query_params": []},
    {"method": 'GET', "path": '/api/Event/:eventId', "title": 'Get an Event', "resource": 'Event', "read": True, "path_params": ['eventId'], "query_params": []},
    {"method": 'PUT', "path": '/api/Event/:eventId', "title": 'Update an Event', "resource": 'Event', "read": False, "path_params": ['eventId'], "query_params": []},
    {"method": 'GET', "path": '/api/Event/:eventId/Attendees', "title": 'Get Event Attendees for an Event', "resource": 'Event', "read": True, "path_params": ['eventId'], "query_params": ['skip', 'take']},
    {"method": 'POST', "path": '/api/Event/:eventId/Attendees', "title": 'Create an Event Attendee', "resource": 'Event', "read": False, "path_params": ['eventId'], "query_params": []},
    {"method": 'DELETE', "path": '/api/Event/:eventId/Attendees/:eventAttendeeId', "title": 'Delete an Event Attendee', "resource": 'Event', "read": False, "path_params": ['eventId', 'eventAttendeeId'], "query_params": []},
    {"method": 'GET', "path": '/api/Event/:eventId/Attendees/:eventAttendeeId', "title": 'Get an Event Attendee', "resource": 'Event', "read": True, "path_params": ['eventId', 'eventAttendeeId'], "query_params": []},
    {"method": 'PUT', "path": '/api/Event/:eventId/Attendees/:eventAttendeeId', "title": 'Update an Event Attendee', "resource": 'Event', "read": False, "path_params": ['eventId', 'eventAttendeeId'], "query_params": []},
    {"method": 'GET', "path": '/api/Event/:eventId/Contacts', "title": 'Get Event Contacts for an Event', "resource": 'Event', "read": True, "path_params": ['eventId'], "query_params": ['skip', 'take']},
    {"method": 'POST', "path": '/api/Event/:eventId/Contacts', "title": 'Create an Event Contact', "resource": 'Event', "read": False, "path_params": ['eventId'], "query_params": []},
    {"method": 'DELETE', "path": '/api/Event/:eventId/Contacts/:eventContactId', "title": 'Delete an Event Contact', "resource": 'Event', "read": False, "path_params": ['eventId', 'eventContactId'], "query_params": []},
    {"method": 'GET', "path": '/api/Event/:eventId/Contacts/:eventContactId', "title": 'Get an Event Contact', "resource": 'Event', "read": True, "path_params": ['eventId', 'eventContactId'], "query_params": []},
    {"method": 'GET', "path": '/api/Event/CustomFields', "title": 'Get Event Custom Fields Available', "resource": 'Event', "read": True, "path_params": [], "query_params": []},
    {"method": 'POST', "path": '/api/Event/Query', "title": 'Query Events', "resource": 'Event', "read": True, "path_params": [], "query_params": ['skip', 'take']},
    {"method": 'GET', "path": '/api/Event/QueryOptions', "title": 'Get Event Query Options', "resource": 'Event', "read": True, "path_params": [], "query_params": []},
    {"method": 'GET', "path": '/api/Event/Search', "title": 'Find an Event', "resource": 'Event', "read": True, "path_params": [], "query_params": ['filter']},
    {"method": 'GET', "path": '/api/Event/Types', "title": 'Get the Event Types', "resource": 'Event', "read": True, "path_params": [], "query_params": []},
    {"method": 'GET', "path": '/api/EventAttendee/CustomFields', "title": 'Get Event Attendee Custom Fields Available', "resource": 'EventAttendee', "read": True, "path_params": [], "query_params": []},
    {"method": 'POST', "path": '/api/EventAttendee/Query', "title": 'Query Event Attendees', "resource": 'EventAttendee', "read": True, "path_params": [], "query_params": ['skip', 'take']},
    {"method": 'GET', "path": '/api/EventAttendee/QueryOptions', "title": 'Get Event Attendee Query Options', "resource": 'EventAttendee', "read": True, "path_params": [], "query_params": []},
    {"method": 'PATCH', "path": '/api/Gift', "title": 'Update many Gifts', "resource": 'Gift', "read": False, "path_params": [], "query_params": []},
    {"method": 'POST', "path": '/api/Gift', "title": 'Create a Gift *not recommended*', "resource": 'Gift', "read": False, "path_params": [], "query_params": []},
    {"method": 'DELETE', "path": '/api/Gift/:giftId', "title": 'Delete a Gift', "resource": 'Gift', "read": False, "path_params": ['giftId'], "query_params": []},
    {"method": 'GET', "path": '/api/Gift/:giftId', "title": 'Get a Gift', "resource": 'Gift', "read": True, "path_params": ['giftId'], "query_params": []},
    {"method": 'PUT', "path": '/api/Gift/:giftId', "title": 'Update a Gift', "resource": 'Gift', "read": False, "path_params": ['giftId'], "query_params": []},
    {"method": 'GET', "path": '/api/Gift/:transactionSource/:transactionId', "title": 'Get a Gift by Transaction Source and ID', "resource": 'Gift', "read": True, "path_params": ['transactionSource', 'transactionId'], "query_params": []},
    {"method": 'POST', "path": '/api/Gift/Bulk', "title": 'Create many Gifts *not recommended*', "resource": 'Gift', "read": False, "path_params": [], "query_params": []},
    {"method": 'GET', "path": '/api/Gift/ByContact/:contactId', "title": 'Get Gifts for a Contact', "resource": 'Gift', "read": True, "path_params": ['contactId'], "query_params": ['sortBy', 'descending', 'skip', 'take']},
    {"method": 'GET', "path": '/api/Gift/ByReference/:referenceId', "title": 'Get Gifts for a Contact by Reference ID', "resource": 'Gift', "read": True, "path_params": ['referenceId'], "query_params": ['skip', 'take', 'excludeReferenceOriginatedGifts']},
    {"method": 'GET', "path": '/api/Gift/CustomFields', "title": 'Get Gift Custom Fields Available', "resource": 'Gift', "read": True, "path_params": [], "query_params": []},
    {"method": 'GET', "path": '/api/Gift/NonCashGiftTypes', "title": 'Get Non-Cash Gift Types Available', "resource": 'Gift', "read": True, "path_params": [], "query_params": ['skip', 'take', 'sortBy', 'descending']},
    {"method": 'GET', "path": '/api/Gift/Passthrough/ByContact/:contactId', "title": 'Get Passthrough Gifts for a Contact', "resource": 'Gift', "read": True, "path_params": ['contactId'], "query_params": ['sortBy', 'descending', 'skip', 'take']},
    {"method": 'POST', "path": '/api/Gift/Query', "title": 'Query Gifts with Abbreviated Details', "resource": 'Gift', "read": True, "path_params": [], "query_params": ['skip', 'take']},
    {"method": 'POST', "path": '/api/Gift/Query/FullGift', "title": 'Query Gifts with Full Details', "resource": 'Gift', "read": True, "path_params": [], "query_params": ['skip', 'take']},
    {"method": 'GET', "path": '/api/Gift/QueryOptions', "title": 'Get Gift Query Options', "resource": 'Gift', "read": True, "path_params": [], "query_params": []},
    {"method": 'POST', "path": '/api/Gift/ReversingTransaction', "title": 'Create a Reversing Transaction', "resource": 'Gift', "read": False, "path_params": [], "query_params": []},
    {"method": 'POST', "path": '/api/v2/Gift/Transaction', "title": 'Create a Gift Transaction', "resource": 'Gift', "read": False, "path_params": [], "query_params": []},
    {"method": 'POST', "path": '/api/v2/Gift/Transactions', "title": 'Create a Batch of Gift Transactions', "resource": 'Gift', "read": False, "path_params": [], "query_params": []},
    {"method": 'POST', "path": '/api/GiftAsk', "title": 'Create a Gift Ask', "resource": 'GiftAsk', "read": False, "path_params": [], "query_params": []},
    {"method": 'GET', "path": '/api/GiftAsk/:giftAskId', "title": 'Get a Gift Ask', "resource": 'GiftAsk', "read": True, "path_params": ['giftAskId'], "query_params": []},
    {"method": 'PUT', "path": '/api/GiftAsk/:giftAskId', "title": 'Update a Gift Ask', "resource": 'GiftAsk', "read": False, "path_params": ['giftAskId'], "query_params": []},
    {"method": 'GET', "path": '/api/GiftAsk/:giftAskId/Gifts', "title": 'Get the Gifts applied to a Gift Ask', "resource": 'GiftAsk', "read": True, "path_params": ['giftAskId'], "query_params": []},
    {"method": 'GET', "path": '/api/GiftAsk/ByContact/:contactId', "title": 'Get Gift Asks for a Contact', "resource": 'GiftAsk', "read": True, "path_params": ['contactId'], "query_params": ['skip', 'take']},
    {"method": 'GET', "path": '/api/GiftAsk/CustomFields', "title": 'Get Gift Ask Custom Fields Available', "resource": 'GiftAsk', "read": True, "path_params": [], "query_params": []},
    {"method": 'POST', "path": '/api/GiftAsk/Query', "title": 'Query Gift Asks', "resource": 'GiftAsk', "read": True, "path_params": [], "query_params": ['skip', 'take']},
    {"method": 'GET', "path": '/api/GiftAsk/QueryOptions', "title": 'Get Gift Ask Query Options', "resource": 'GiftAsk', "read": True, "path_params": [], "query_params": []},
    {"method": 'POST', "path": '/api/GiftDesignation/Query', "title": 'Query Gift Designations', "resource": 'GiftDesignation', "read": True, "path_params": [], "query_params": ['skip', 'take']},
    {"method": 'GET', "path": '/api/GiftDesignation/QueryOptions', "title": 'Get Gift Designation Query Options', "resource": 'GiftDesignation', "read": True, "path_params": [], "query_params": []},
    {"method": 'POST', "path": '/api/Grant', "title": 'Create a Grant', "resource": 'Grant', "read": False, "path_params": [], "query_params": []},
    {"method": 'DELETE', "path": '/api/Grant/:grantId', "title": 'Delete a Grant', "resource": 'Grant', "read": False, "path_params": ['grantId'], "query_params": []},
    {"method": 'GET', "path": '/api/Grant/:grantId', "title": 'Get Grant', "resource": 'Grant', "read": True, "path_params": ['grantId'], "query_params": []},
    {"method": 'PUT', "path": '/api/Grant/:grantId', "title": 'Update a Grant', "resource": 'Grant', "read": False, "path_params": ['grantId'], "query_params": []},
    {"method": 'GET', "path": '/api/Grant/:grantId/Gifts', "title": 'Get the Gifts applied to a Grant', "resource": 'Grant', "read": True, "path_params": ['grantId'], "query_params": []},
    {"method": 'GET', "path": '/api/Grant/ByContact/:contactId', "title": 'Get Grants for a Contact', "resource": 'Grant', "read": True, "path_params": ['contactId'], "query_params": ['skip', 'take']},
    {"method": 'GET', "path": '/api/Grant/ByReference/:referenceId', "title": 'Get a Grant by Reference ID', "resource": 'Grant', "read": True, "path_params": ['referenceId'], "query_params": []},
    {"method": 'GET', "path": '/api/Grant/CustomFields', "title": 'Get Grant Custom Fields Available', "resource": 'Grant', "read": True, "path_params": [], "query_params": []},
    {"method": 'POST', "path": '/api/Grant/Query', "title": 'Query Grants', "resource": 'Grant', "read": True, "path_params": [], "query_params": ['skip', 'take']},
    {"method": 'GET', "path": '/api/Grant/QueryOptions', "title": 'Get Grant Query Options', "resource": 'Grant', "read": True, "path_params": [], "query_params": []},
    {"method": 'GET', "path": '/api/Organization', "title": 'Get the Organizations the current user belongs to', "resource": 'Organization', "read": True, "path_params": [], "query_params": []},
    {"method": 'GET', "path": '/api/Organization/Current', "title": 'Get the Current Organization for the current user', "resource": 'Organization', "read": True, "path_params": [], "query_params": []},
    {"method": 'PUT', "path": '/api/Organization/Switch', "title": 'Switch the Current Organization', "resource": 'Organization', "read": False, "path_params": [], "query_params": []},
    {"method": 'GET', "path": '/api/OrganizationGroup', "title": 'Get all Organization Groups', "resource": 'OrganizationGroup', "read": True, "path_params": [], "query_params": ['filter', 'skip', 'take']},
    {"method": 'GET', "path": '/api/OrganizationGroup/:organizationGroupId', "title": 'Get an Organization Group', "resource": 'OrganizationGroup', "read": True, "path_params": ['organizationGroupId'], "query_params": []},
    {"method": 'GET', "path": '/api/OrganizationGroup/:organizationGroupId/contacts', "title": 'Get the Contacts in an Organization Group', "resource": 'OrganizationGroup', "read": True, "path_params": ['organizationGroupId'], "query_params": ['skip', 'take']},
    {"method": 'DELETE', "path": '/api/OrganizationGroup/:organizationGroupId/contacts/:contactId', "title": 'Remove a Contact from an Organization Group', "resource": 'OrganizationGroup', "read": False, "path_params": ['organizationGroupId', 'contactId'], "query_params": []},
    {"method": 'PUT', "path": '/api/OrganizationGroup/:organizationGroupId/contacts/:contactId', "title": 'Assign a Contact to an Organization Group', "resource": 'OrganizationGroup', "read": False, "path_params": ['organizationGroupId', 'contactId'], "query_params": []},
    {"method": 'GET', "path": '/api/OrganizationGroup/ByContact/:contactId', "title": 'Get Organization Groups for a Contact', "resource": 'OrganizationGroup', "read": True, "path_params": ['contactId'], "query_params": []},
    {"method": 'GET', "path": '/api/Permission', "title": 'Get Permissions for the current user', "resource": 'Permission', "read": True, "path_params": [], "query_params": []},
    {"method": 'POST', "path": '/api/PlannedGift', "title": 'Create a Planned Gift', "resource": 'PlannedGift', "read": False, "path_params": [], "query_params": []},
    {"method": 'GET', "path": '/api/PlannedGift/:plannedGiftId', "title": 'Get Planned Gift', "resource": 'PlannedGift', "read": True, "path_params": ['plannedGiftId'], "query_params": []},
    {"method": 'PUT', "path": '/api/PlannedGift/:plannedGiftId', "title": 'Update a Planned Gift', "resource": 'PlannedGift', "read": False, "path_params": ['plannedGiftId'], "query_params": []},
    {"method": 'GET', "path": '/api/PlannedGift/:plannedGiftId/Gifts', "title": 'Get Gifts Applied to a Planned Gift', "resource": 'PlannedGift', "read": True, "path_params": ['plannedGiftId'], "query_params": []},
    {"method": 'GET', "path": '/api/PlannedGift/ByContact/:contactId', "title": 'Get Planned Gifts for a Contact', "resource": 'PlannedGift', "read": True, "path_params": ['contactId'], "query_params": ['skip', 'take']},
    {"method": 'GET', "path": '/api/PlannedGift/CustomFields', "title": 'Get Planned Gift Custom Fields Available', "resource": 'PlannedGift', "read": True, "path_params": [], "query_params": []},
    {"method": 'POST', "path": '/api/PlannedGift/Query', "title": 'Query Planned Gifts', "resource": 'PlannedGift', "read": True, "path_params": [], "query_params": ['skip', 'take']},
    {"method": 'GET', "path": '/api/PlannedGift/QueryOptions', "title": 'Get Planned Gift Query Options', "resource": 'PlannedGift', "read": True, "path_params": [], "query_params": []},
    {"method": 'POST', "path": '/api/v2/Pledge', "title": 'Create a Pledge', "resource": 'Pledge', "read": False, "path_params": [], "query_params": []},
    {"method": 'GET', "path": '/api/v2/Pledge/:pledgeId', "title": 'Get Pledge', "resource": 'Pledge', "read": True, "path_params": ['pledgeId'], "query_params": []},
    {"method": 'PUT', "path": '/api/v2/Pledge/:pledgeId', "title": 'Update a Pledge', "resource": 'Pledge', "read": False, "path_params": ['pledgeId'], "query_params": []},
    {"method": 'GET', "path": '/api/v2/Pledge/ByContact/:contactId', "title": 'Get Pledges for a Contact', "resource": 'Pledge', "read": True, "path_params": ['contactId'], "query_params": ['sortBy', 'descending', 'skip', 'take']},
    {"method": 'GET', "path": '/api/v2/Pledge/CustomFields', "title": 'Get Pledge Custom Fields Available', "resource": 'Pledge', "read": True, "path_params": [], "query_params": []},
    {"method": 'POST', "path": '/api/v2/Pledge/Query', "title": 'Query Pledges', "resource": 'Pledge', "read": True, "path_params": [], "query_params": ['skip', 'take']},
    {"method": 'GET', "path": '/api/v2/Pledge/QueryOptions', "title": 'Get Pledge Query Options', "resource": 'Pledge', "read": True, "path_params": [], "query_params": []},
    {"method": 'PUT', "path": '/api/v2/Pledge/WriteOff/:pledgeId', "title": 'Write-off the Pledge', "resource": 'Pledge', "read": False, "path_params": ['pledgeId'], "query_params": []},
    {"method": 'POST', "path": '/api/Premium', "title": 'Create a Premium', "resource": 'Premium', "read": False, "path_params": [], "query_params": []},
    {"method": 'GET', "path": '/api/Premium/:premiumId', "title": 'Get Premium', "resource": 'Premium', "read": True, "path_params": ['premiumId'], "query_params": []},
    {"method": 'PUT', "path": '/api/Premium/:premiumId', "title": 'Update a Premium', "resource": 'Premium', "read": False, "path_params": ['premiumId'], "query_params": []},
    {"method": 'GET', "path": '/api/Premium/Code/:premiumCode', "title": 'Get Premium using a unique Code', "resource": 'Premium', "read": True, "path_params": ['premiumCode'], "query_params": []},
    {"method": 'GET', "path": '/api/Premium/CustomFields', "title": 'Get Premium Custom Fields Available', "resource": 'Premium', "read": True, "path_params": [], "query_params": []},
    {"method": 'PUT', "path": '/api/Premium/Decrement/:premiumId', "title": 'Decrement the inventory count', "resource": 'Premium', "read": False, "path_params": ['premiumId'], "query_params": ['decrementor']},
    {"method": 'PUT', "path": '/api/Premium/Increment/:premiumId', "title": 'Increment the inventory count', "resource": 'Premium', "read": False, "path_params": ['premiumId'], "query_params": ['incrementor']},
    {"method": 'POST', "path": '/api/Premium/Query', "title": 'Query Premiums', "resource": 'Premium', "read": True, "path_params": [], "query_params": ['skip', 'take']},
    {"method": 'GET', "path": '/api/Premium/QueryOptions', "title": 'Get Premium Query Options', "resource": 'Premium', "read": True, "path_params": [], "query_params": []},
    {"method": 'POST', "path": '/api/Premium/Search', "title": 'Find Premiums', "resource": 'Premium', "read": True, "path_params": [], "query_params": ['skip', 'take']},
    {"method": 'PATCH', "path": '/api/Project', "title": 'Update many Projects', "resource": 'Project', "read": False, "path_params": [], "query_params": []},
    {"method": 'POST', "path": '/api/Project', "title": 'Create a Project', "resource": 'Project', "read": False, "path_params": [], "query_params": ['disableWebhookUpdates']},
    {"method": 'GET', "path": '/api/Project/:projectId', "title": 'Get Project', "resource": 'Project', "read": True, "path_params": ['projectId'], "query_params": []},
    {"method": 'PUT', "path": '/api/Project/:projectId', "title": 'Update a Project', "resource": 'Project', "read": False, "path_params": ['projectId'], "query_params": ['disableWebhookUpdates']},
    {"method": 'PUT', "path": '/api/Project/:projectId/Balance', "title": 'Update Project Balance', "resource": 'Project', "read": False, "path_params": ['projectId'], "query_params": []},
    {"method": 'PUT', "path": '/api/Project/:projectId/Status', "title": 'Temporarily Change Project Inventory Status', "resource": 'Project', "read": False, "path_params": ['projectId'], "query_params": ['inventoryStatus', 'durationMinutes']},
    {"method": 'GET', "path": '/api/Project/Code/:projectCode', "title": 'Get a Project using a unique Code', "resource": 'Project', "read": True, "path_params": ['projectCode'], "query_params": []},
    {"method": 'GET', "path": '/api/Project/CustomFields', "title": 'Get Project Custom Fields Available', "resource": 'Project', "read": True, "path_params": [], "query_params": []},
    {"method": 'POST', "path": '/api/Project/Query', "title": 'Query Projects', "resource": 'Project', "read": True, "path_params": [], "query_params": ['skip', 'take']},
    {"method": 'GET', "path": '/api/Project/QueryOptions', "title": 'Get Project Query Options', "resource": 'Project', "read": True, "path_params": [], "query_params": []},
    {"method": 'POST', "path": '/api/Project/Search', "title": 'Find Projects', "resource": 'Project', "read": True, "path_params": [], "query_params": ['skip', 'take']},
    {"method": 'GET', "path": '/api/Project/Types', "title": 'Get Project Types', "resource": 'Project', "read": True, "path_params": [], "query_params": []},
    {"method": 'GET', "path": '/api/ProjectExpense', "title": 'Get Project Expenses for a Project', "resource": 'ProjectExpense', "read": True, "path_params": [], "query_params": ['projectId', 'projectCode', 'filter', 'take', 'count']},
    {"method": 'POST', "path": '/api/ProjectExpense', "title": 'Create a Project Expense', "resource": 'ProjectExpense', "read": False, "path_params": [], "query_params": []},
    {"method": 'GET', "path": '/api/ProjectExpense/:projectExpenseId', "title": 'Get Project Expense', "resource": 'ProjectExpense', "read": True, "path_params": ['projectExpenseId'], "query_params": []},
    {"method": 'PUT', "path": '/api/ProjectExpense/:projectExpenseId', "title": 'Update a Project Expense', "resource": 'ProjectExpense', "read": False, "path_params": ['projectExpenseId'], "query_params": []},
    {"method": 'POST', "path": '/api/ProjectExpense/Batch', "title": 'Create many Project Expenses', "resource": 'ProjectExpense', "read": False, "path_params": [], "query_params": []},
    {"method": 'POST', "path": '/api/ProjectNote', "title": 'Create a Project Note', "resource": 'ProjectNote', "read": False, "path_params": [], "query_params": []},
    {"method": 'DELETE', "path": '/api/ProjectNote/:noteId', "title": 'Delete a Project Note', "resource": 'ProjectNote', "read": False, "path_params": ['noteId'], "query_params": []},
    {"method": 'GET', "path": '/api/ProjectNote/:noteId', "title": 'Get Project Note', "resource": 'ProjectNote', "read": True, "path_params": ['noteId'], "query_params": []},
    {"method": 'PUT', "path": '/api/ProjectNote/:noteId', "title": 'Update a Project Note', "resource": 'ProjectNote', "read": False, "path_params": ['noteId'], "query_params": []},
    {"method": 'GET', "path": '/api/ProjectNote/ByProject/:projectId', "title": 'Get Notes for a Project', "resource": 'ProjectNote', "read": True, "path_params": ['projectId'], "query_params": ['skip', 'take']},
    {"method": 'GET', "path": '/api/ProjectNote/Types', "title": 'Get Project Note Types', "resource": 'ProjectNote', "read": True, "path_params": [], "query_params": []},
    {"method": 'POST', "path": '/api/ProjectRole', "title": 'Create a Project Role', "resource": 'ProjectRole', "read": False, "path_params": [], "query_params": []},
    {"method": 'DELETE', "path": '/api/ProjectRole/:projectRoleId', "title": 'Delete a Project Role', "resource": 'ProjectRole', "read": False, "path_params": ['projectRoleId'], "query_params": []},
    {"method": 'GET', "path": '/api/ProjectRole/:projectRoleId', "title": 'Get Project Role', "resource": 'ProjectRole', "read": True, "path_params": ['projectRoleId'], "query_params": []},
    {"method": 'PUT', "path": '/api/ProjectRole/:projectRoleId', "title": 'Update a Project Role', "resource": 'ProjectRole', "read": False, "path_params": ['projectRoleId'], "query_params": []},
    {"method": 'GET', "path": '/api/ProjectRole/ByContact/:contactId', "title": 'Get Project Roles for a Contact', "resource": 'ProjectRole', "read": True, "path_params": ['contactId'], "query_params": ['skip', 'take']},
    {"method": 'GET', "path": '/api/ProjectRole/ByProject/:projectId', "title": 'Get Project Roles for a Project', "resource": 'ProjectRole', "read": True, "path_params": ['projectId'], "query_params": ['skip', 'take']},
    {"method": 'GET', "path": '/api/ProjectRole/Types', "title": 'Get Project Role Types', "resource": 'ProjectRole', "read": True, "path_params": [], "query_params": ['skip', 'take']},
    {"method": 'POST', "path": '/api/RecurringGift', "title": 'Create a Recurring Gift', "resource": 'RecurringGift', "read": False, "path_params": [], "query_params": []},
    {"method": 'GET', "path": '/api/RecurringGift/:recurringGiftId', "title": 'Get a Recurring Gift', "resource": 'RecurringGift', "read": True, "path_params": ['recurringGiftId'], "query_params": []},
    {"method": 'PUT', "path": '/api/RecurringGift/:recurringGiftId', "title": 'Update a Recurring Gift', "resource": 'RecurringGift', "read": False, "path_params": ['recurringGiftId'], "query_params": []},
    {"method": 'GET', "path": '/api/RecurringGift/ByContact/:contactId', "title": 'Get Recurring Gifts for a Contact', "resource": 'RecurringGift', "read": True, "path_params": ['contactId'], "query_params": ['sortBy', 'descending', 'skip', 'take']},
    {"method": 'PUT', "path": '/api/RecurringGift/Cancel/:recurringGiftId', "title": 'Cancel a Recurring Gift', "resource": 'RecurringGift', "read": False, "path_params": ['recurringGiftId'], "query_params": []},
    {"method": 'GET', "path": '/api/RecurringGift/CustomFields', "title": 'Get Recurring Gift Custom Fields Available', "resource": 'RecurringGift', "read": True, "path_params": [], "query_params": []},
    {"method": 'POST', "path": '/api/RecurringGift/Query', "title": 'Query Recurring Gifts', "resource": 'RecurringGift', "read": True, "path_params": [], "query_params": ['skip', 'take']},
    {"method": 'GET', "path": '/api/RecurringGift/QueryOptions', "title": 'Get Recurring Gift Query Options', "resource": 'RecurringGift', "read": True, "path_params": [], "query_params": []},
    {"method": 'GET', "path": '/api/RecurringGiftPayment/:recurringGiftId', "title": 'Get Payments for a Recurring Gift', "resource": 'RecurringGiftPayment', "read": True, "path_params": ['recurringGiftId'], "query_params": ['skip', 'take']},
    {"method": 'POST', "path": '/api/Relationship', "title": 'Create a Relationship', "resource": 'Relationship', "read": False, "path_params": [], "query_params": []},
    {"method": 'DELETE', "path": '/api/Relationship/:relationshipId', "title": 'Delete a Relationship', "resource": 'Relationship', "read": False, "path_params": ['relationshipId'], "query_params": []},
    {"method": 'PUT', "path": '/api/Relationship/:relationshipId', "title": 'Update a Relationship', "resource": 'Relationship', "read": False, "path_params": ['relationshipId'], "query_params": []},
    {"method": 'GET', "path": '/api/Relationship/ByContact/:contactId', "title": 'Get Relationships for a Contact', "resource": 'Relationship', "read": True, "path_params": ['contactId'], "query_params": ['skip', 'take']},
    {"method": 'GET', "path": '/api/Relationship/Types', "title": 'Get Relationship Types', "resource": 'Relationship', "read": True, "path_params": [], "query_params": []},
    {"method": 'POST', "path": '/api/Reminder', "title": 'Create Manual Reminder', "resource": 'Reminder', "read": False, "path_params": [], "query_params": []},
    {"method": 'GET', "path": '/api/Reminder/Active', "title": 'Get Active Reminders (for current user)', "resource": 'Reminder', "read": True, "path_params": [], "query_params": ['skip', 'take', 'search.search']},
    {"method": 'GET', "path": '/api/Reminder/ByContact/:contactId', "title": 'Get Unresolved Manual Reminders by Contact', "resource": 'Reminder', "read": True, "path_params": ['contactId'], "query_params": ['skip', 'take']},
    {"method": 'GET', "path": '/api/Reminder/ByContact/:contactId/Active', "title": 'Get Active Manual Reminders by Contact', "resource": 'Reminder', "read": True, "path_params": ['contactId'], "query_params": ['skip', 'take']},
    {"method": 'GET', "path": '/api/Reminder/ByContact/:contactId/Inactive', "title": 'Get Inactive Manual Reminders by Contact', "resource": 'Reminder', "read": True, "path_params": ['contactId'], "query_params": ['skip', 'take']},
    {"method": 'PUT', "path": '/api/Reminder/Completed/:id', "title": 'Complete Reminder', "resource": 'Reminder', "read": False, "path_params": ['id'], "query_params": []},
    {"method": 'PUT', "path": '/api/Reminder/Dismissed/:id', "title": 'Dismiss Reminder', "resource": 'Reminder', "read": False, "path_params": ['id'], "query_params": []},
    {"method": 'GET', "path": '/api/Reminder/Saved', "title": 'Get Saved Reminders (for current user)', "resource": 'Reminder', "read": True, "path_params": [], "query_params": ['skip', 'take']},
    {"method": 'POST', "path": '/api/Reminder/Saved/Milestone', "title": 'Create Milestone Reminder', "resource": 'Reminder', "read": False, "path_params": [], "query_params": []},
    {"method": 'PUT', "path": '/api/Reminder/Saved/Milestone/:id', "title": 'Update Milestone Reminder.', "resource": 'Reminder', "read": False, "path_params": ['id'], "query_params": []},
    {"method": 'POST', "path": '/api/Reminder/Saved/Recurring', "title": 'Create Recurring Reminder', "resource": 'Reminder', "read": False, "path_params": [], "query_params": []},
    {"method": 'PUT', "path": '/api/Reminder/Saved/Recurring/:id', "title": 'Update Recurring Reminder', "resource": 'Reminder', "read": False, "path_params": ['id'], "query_params": []},
    {"method": 'GET', "path": '/api/Reminder/Type/Milestone', "title": 'Gets Milestone Types', "resource": 'Reminder', "read": True, "path_params": [], "query_params": []},
    {"method": 'GET', "path": '/api/Reminder/Type/Reminder', "title": 'Get Reminder Types', "resource": 'Reminder', "read": True, "path_params": [], "query_params": []},
    {"method": 'GET', "path": '/api/Reminder/Type/ReminderFrequency', "title": 'Gets Reminder Frequency Types', "resource": 'Reminder', "read": True, "path_params": [], "query_params": []},
    {"method": 'GET', "path": '/api/Reminder/Type/ReminderSource', "title": 'Get Reminder Source Types', "resource": 'Reminder', "read": True, "path_params": [], "query_params": []},
    {"method": 'POST', "path": '/api/Search', "title": 'Search for Contacts, Individuals or Entities', "resource": 'Search', "read": True, "path_params": [], "query_params": ['skip', 'take']},
    {"method": 'POST', "path": '/api/Segment', "title": 'Create a Segment', "resource": 'Segment', "read": False, "path_params": [], "query_params": []},
    {"method": 'GET', "path": '/api/Segment/:segmentId', "title": 'Get a Segment', "resource": 'Segment', "read": True, "path_params": ['segmentId'], "query_params": []},
    {"method": 'PUT', "path": '/api/Segment/:segmentId', "title": 'Update a Segment', "resource": 'Segment', "read": False, "path_params": ['segmentId'], "query_params": []},
    {"method": 'GET', "path": '/api/Segment/ByContact/:contactId', "title": 'Get the Segments for a Contact', "resource": 'Segment', "read": True, "path_params": ['contactId'], "query_params": ['skip', 'take']},
    {"method": 'GET', "path": '/api/Segment/Code/:segmentCode', "title": 'Get a Segment using a unique Code', "resource": 'Segment', "read": True, "path_params": ['segmentCode'], "query_params": []},
    {"method": 'POST', "path": '/api/Segment/Search', "title": 'Find Segments', "resource": 'Segment', "read": True, "path_params": [], "query_params": ['skip', 'take']},
    {"method": 'GET', "path": '/api/Tag', "title": 'Get all Tags', "resource": 'Tag', "read": True, "path_params": [], "query_params": ['skip', 'take']},
    {"method": 'POST', "path": '/api/Tag/Search', "title": 'Find all Tags that match, fully or partially', "resource": 'Tag', "read": True, "path_params": [], "query_params": ['skip', 'take']},
    {"method": 'POST', "path": '/api/Task', "title": 'Create a Task', "resource": 'Task', "read": False, "path_params": [], "query_params": []},
    {"method": 'POST', "path": '/api/Task/Query', "title": 'Query Tasks', "resource": 'Task', "read": True, "path_params": [], "query_params": ['skip', 'take']},
    {"method": 'GET', "path": '/api/Task/QueryOptions', "title": 'Get Task Query Options', "resource": 'Task', "read": True, "path_params": [], "query_params": []},
    {"method": 'GET', "path": '/api/Task/Types', "title": 'Get Task Types', "resource": 'Task', "read": True, "path_params": [], "query_params": []},
    {"method": 'POST', "path": '/api/Tribute', "title": 'Create a Tribute', "resource": 'Tribute', "read": False, "path_params": [], "query_params": []},
    {"method": 'PUT', "path": '/api/Tribute/:tributeId', "title": 'Update a Tribute', "resource": 'Tribute', "read": False, "path_params": ['tributeId'], "query_params": []},
    {"method": 'GET', "path": '/api/Tribute/Search', "title": 'Search for Tributes', "resource": 'Tribute', "read": True, "path_params": [], "query_params": ['firstName', 'lastName', 'city', 'state', 'tributeType']},
    {"method": 'POST', "path": '/api/Volunteer/Query', "title": 'Query Volunteers', "resource": 'Volunteer', "read": True, "path_params": [], "query_params": []},
    {"method": 'GET', "path": '/api/Volunteer/QueryOptions', "title": 'Get Query Options', "resource": 'Volunteer', "read": True, "path_params": [], "query_params": []},
    {"method": 'GET', "path": '/api/Volunteer/Search', "title": 'Search for Volunteers', "resource": 'Volunteer', "read": True, "path_params": [], "query_params": ['volunteerOpportunityId', 'volunteerId', 'contactId', 'contactIndividualId', 'emailAddress', 'skip', 'take']},
    {"method": 'GET', "path": '/api/VolunteerOpportunity', "title": 'Get Volunteer Opportunities', "resource": 'VolunteerOpportunity', "read": True, "path_params": [], "query_params": ['filter', 'skip', 'take']},
    {"method": 'POST', "path": '/api/VolunteerOpportunity', "title": 'Create a Volunteer Opportunity', "resource": 'VolunteerOpportunity', "read": False, "path_params": [], "query_params": []},
    {"method": 'DELETE', "path": '/api/VolunteerOpportunity/:volunteerOpportunityId', "title": 'Delete a Volunteer Opportunity', "resource": 'VolunteerOpportunity', "read": False, "path_params": ['volunteerOpportunityId'], "query_params": []},
    {"method": 'GET', "path": '/api/VolunteerOpportunity/:volunteerOpportunityId', "title": 'Get Volunteer Opportunity', "resource": 'VolunteerOpportunity', "read": True, "path_params": ['volunteerOpportunityId'], "query_params": []},
    {"method": 'PUT', "path": '/api/VolunteerOpportunity/:volunteerOpportunityId', "title": 'Update a Volunteer Opportunity', "resource": 'VolunteerOpportunity', "read": False, "path_params": ['volunteerOpportunityId'], "query_params": []},
    {"method": 'DELETE', "path": '/api/VolunteerOpportunity/:volunteerOpportunityId/Attendance/:volunteerAttendanceId', "title": 'Delete a Volunteer Attendance', "resource": 'VolunteerOpportunity', "read": False, "path_params": ['volunteerOpportunityId', 'volunteerAttendanceId'], "query_params": []},
    {"method": 'GET', "path": '/api/VolunteerOpportunity/:volunteerOpportunityId/Attendance/:volunteerAttendanceId', "title": 'Get Volunteer Attendance', "resource": 'VolunteerOpportunity', "read": True, "path_params": ['volunteerOpportunityId', 'volunteerAttendanceId'], "query_params": []},
    {"method": 'PUT', "path": '/api/VolunteerOpportunity/:volunteerOpportunityId/Attendance/:volunteerAttendanceId', "title": 'Update a Volunteer Attendance', "resource": 'VolunteerOpportunity', "read": False, "path_params": ['volunteerOpportunityId', 'volunteerAttendanceId'], "query_params": []},
    {"method": 'GET', "path": '/api/VolunteerOpportunity/:volunteerOpportunityId/Organizers', "title": 'Get Volunteer Organizers', "resource": 'VolunteerOpportunity', "read": True, "path_params": ['volunteerOpportunityId'], "query_params": []},
    {"method": 'POST', "path": '/api/VolunteerOpportunity/:volunteerOpportunityId/Organizers', "title": 'Create a Volunteer Organizer', "resource": 'VolunteerOpportunity', "read": False, "path_params": ['volunteerOpportunityId'], "query_params": []},
    {"method": 'DELETE', "path": '/api/VolunteerOpportunity/:volunteerOpportunityId/Organizers/:volunteerOrganizerId', "title": 'Delete a Volunteer Organizer', "resource": 'VolunteerOpportunity', "read": False, "path_params": ['volunteerOpportunityId', 'volunteerOrganizerId'], "query_params": []},
    {"method": 'GET', "path": '/api/VolunteerOpportunity/:volunteerOpportunityId/Organizers/:volunteerOrganizerId', "title": 'Get Volunteer Organizer', "resource": 'VolunteerOpportunity', "read": True, "path_params": ['volunteerOpportunityId', 'volunteerOrganizerId'], "query_params": []},
    {"method": 'GET', "path": '/api/VolunteerOpportunity/:volunteerOpportunityId/Volunteers', "title": 'Get Volunteers for a Volunteer Opportunity', "resource": 'VolunteerOpportunity', "read": True, "path_params": ['volunteerOpportunityId'], "query_params": ['skip', 'take']},
    {"method": 'POST', "path": '/api/VolunteerOpportunity/:volunteerOpportunityId/Volunteers', "title": 'Create a Volunteer', "resource": 'VolunteerOpportunity', "read": False, "path_params": ['volunteerOpportunityId'], "query_params": []},
    {"method": 'DELETE', "path": '/api/VolunteerOpportunity/:volunteerOpportunityId/Volunteers/:volunteerId', "title": 'Delete a Volunteer', "resource": 'VolunteerOpportunity', "read": False, "path_params": ['volunteerOpportunityId', 'volunteerId'], "query_params": []},
    {"method": 'GET', "path": '/api/VolunteerOpportunity/:volunteerOpportunityId/Volunteers/:volunteerId', "title": 'Get Volunteer', "resource": 'VolunteerOpportunity', "read": True, "path_params": ['volunteerOpportunityId', 'volunteerId'], "query_params": []},
    {"method": 'GET', "path": '/api/VolunteerOpportunity/:volunteerOpportunityId/Volunteers/:volunteerId/Attendance', "title": 'Get Volunteer Attendance for a Volunteer', "resource": 'VolunteerOpportunity', "read": True, "path_params": ['volunteerOpportunityId', 'volunteerId'], "query_params": []},
    {"method": 'POST', "path": '/api/VolunteerOpportunity/:volunteerOpportunityId/Volunteers/:volunteerId/Attendance', "title": 'Create a Volunteer Attendance', "resource": 'VolunteerOpportunity', "read": False, "path_params": ['volunteerOpportunityId', 'volunteerId'], "query_params": []},
    {"method": 'GET', "path": '/api/VolunteerOpportunity/CustomFields', "title": 'Get Custom Fields Available', "resource": 'VolunteerOpportunity', "read": True, "path_params": [], "query_params": []},
    {"method": 'POST', "path": '/api/VolunteerOpportunity/Query', "title": 'Queries Volunteer Opportunities', "resource": 'VolunteerOpportunity', "read": True, "path_params": [], "query_params": []},
    {"method": 'GET', "path": '/api/VolunteerOpportunity/QueryOptions', "title": 'Get Query Options', "resource": 'VolunteerOpportunity', "read": True, "path_params": [], "query_params": []},
    {"method": 'POST', "path": '/api/Webhook', "title": 'Create a Webhook', "resource": 'Webhook', "read": False, "path_params": [], "query_params": []},
    {"method": 'DELETE', "path": '/api/Webhook/:webhookId', "title": 'Delete a Webhook', "resource": 'Webhook', "read": False, "path_params": ['webhookId'], "query_params": []},
    {"method": 'GET', "path": '/api/Webhook/:webhookId', "title": 'Get a Webhook', "resource": 'Webhook', "read": True, "path_params": ['webhookId'], "query_params": []},
    {"method": 'PUT', "path": '/api/Webhook/:webhookId', "title": 'Update a Webhook', "resource": 'Webhook', "read": False, "path_params": ['webhookId'], "query_params": []},
    {"method": 'PUT', "path": '/api/Webhook/:webhookId/Active', "title": 'Set the active state of a Webhook', "resource": 'Webhook', "read": False, "path_params": ['webhookId'], "query_params": ['active']},
]

RESOURCES: list[str] = sorted({e["resource"] for e in ENDPOINTS})


def find_endpoint(method: str, path_template: str) -> Endpoint | None:
    """Look up an endpoint by exact method + path template (with :placeholders)."""
    method = method.upper()
    for e in ENDPOINTS:
        if e["method"] == method and e["path"] == path_template:
            return e
    return None
